version: '3.4'

services:
    cache:
        image: redis:6.2-alpine
        restart: always
        ports:
            - "6379:6379"
        command: redis-server --save 20 1 --loglevel warning --requirepass eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
    traceip:
        image: traceip-backend
        build:
            context: .
            dockerfile: Dockerfile
        environment:
            SERVER_IP: "127.0.0.1"
            REDIS_HOST: cache
            REDIS_PORT: 6379
            REDIS_PASSWORD: eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
        ports:
            - "5000:80"
        depends_on:
            - cache
volumes:
  trace_ip_vol: